spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  cloud:
    config:
      name: twitter-to-kafka-server,config-client
      username: spring_cloud_user
      password: spr1Ng.Cl0ud