server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mibexx/demo-microservice-config.git
          username: mibexx
          clone-on-start: true
          default-label: main
    fail-fast: true
  security:
    user:
      name: spring_cloud_user
      password: '{cipher}2476c863ffbfb1029d44363c07e8d949b3f9a727de9ccfd036f575aa6deebd92'

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG